In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("Datasets/homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

np.float64(180616.43835616432)

In [6]:
model.predict([[5000]])

/Users/sudiptoray/Developer/LearnML/ML_venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [7]:
model.predict(pd.DataFrame([[5000]],columns=['area']))

array([859554.79452055])

### Save Model To a File Using Python Pickle

In [8]:
import pickle

In [9]:
with open('Output/model_pickle','wb') as file:
    pickle.dump(model,file)

### Load Saved Model

In [10]:
with open('Output/model_pickle','rb') as file:
    mp = pickle.load(file)

In [11]:
mp.coef_

array([135.78767123])

In [12]:
mp.intercept_

np.float64(180616.43835616432)

In [13]:
mp.intercept_

np.float64(180616.43835616432)